EXTERNAL setTheme(theme)
EXTERNAL keepSoundAlive()
EXTERNAL createSlot(name, loop, groupList)
EXTERNAL loadSound(slot, sound, url)
EXTERNAL playSound(slot, sound, volume, crossFade)
EXTERNAL playSoundV(slot, sound, volume)
EXTERNAL playSoundS(slot, sound)
EXTERNAL stopSound(slot)
EXTERNAL currentSound(slot)
EXTERNAL hasFrontend()
EXTERNAL activity()